#!/usr/bin/env python3
"""Provision the notification template, contact point, and policy route."""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

from config import CONTACT_POINT, MANAGED_BY
from grafana_client import (
    GrafanaClient,
    GrafanaError,
    configure_logging,
    emit_result,
)
from teams_webhook_config import TeamsWebhookConfigError, load_dotenv_if_present, resolve_webhook_url

TEMPLATE_NAME = "teams-default"
TEMPLATE_PATH = ROOT / "templates" / "teams-default.tmpl"
CONTACT_POINT_NAME = CONTACT_POINT


def ensure_template(client: GrafanaClient, *, dry_run: bool) -> dict:
    body = TEMPLATE_PATH.read_text(encoding="utf-8")
    # Grafana provisioning API expects the template body without the outer define wrappers
    # when using PUT /templates/{name}, but our file already contains define blocks named
    # teams-default.title / .message. Pass the whole file as the template group body.
    if dry_run:
        return {"action": "would_create", "name": TEMPLATE_NAME, "bytes": len(body)}
    client.create_notification_template(TEMPLATE_NAME, body)
    return {"action": "upserted", "name": TEMPLATE_NAME, "bytes": len(body)}


def ensure_contact_point(client: GrafanaClient, webhook: str, *, dry_run: bool) -> dict:
    payload = {
        "name": CONTACT_POINT_NAME,
        "type": "webhook",
        "settings": {
            "url": webhook,
            "httpMethod": "POST",
        },
        "disableResolveMessage": False,
    }
    existing = client.list_contact_points() if not dry_run else []
    match = next((p for p in existing if p.get("name") == CONTACT_POINT_NAME), None)
    if dry_run:
        return {
            "action": "would_update" if match else "would_create",
            "name": CONTACT_POINT_NAME,
        }
    if match and match.get("uid"):
        result = client.update_contact_point(match["uid"], payload)
        return {"action": "updated", "name": CONTACT_POINT_NAME, "uid": match["uid"], "result_uid": (result or {}).get("uid")}
    result = client.upsert_contact_point(payload)
    return {"action": "created", "name": CONTACT_POINT_NAME, "uid": (result or {}).get("uid")}


def ensure_policy(client: GrafanaClient, *, dry_run: bool) -> dict:
    current = client.get_notification_policies()
    tree = copy.deepcopy(current) if isinstance(current, dict) else {"receiver": "empty", "group_by": ["grafana_folder", "alertname"]}
    routes = list(tree.get("routes") or [])

    desired = {
        "receiver": CONTACT_POINT_NAME,
        "object_matchers": [["managed_by", "=", MANAGED_BY]],
        "group_by": ["alertname", "severity", "resource"],
        "group_wait": "30s",
        "group_interval": "5m",
        "repeat_interval": "4h",
    }

    # Keep autogenerated routes; replace or append the managed_by route.
    new_routes = []
    replaced = False
    for route in routes:
        matchers = route.get("object_matchers") or route.get("matchers") or []
        is_ours = any(
            isinstance(m, list) and len(m) >= 3 and m[0] == "managed_by" and m[2] == MANAGED_BY
            for m in matchers
        )
        if is_ours:
            new_routes.append(desired)
            replaced = True
        else:
            new_routes.append(route)
    if not replaced:
        new_routes.append(desired)
    tree["routes"] = new_routes

    if dry_run:
        return {"action": "would_put", "routes": len(new_routes), "tree": tree}
    client.put_notification_policies(tree)
    return {"action": "put", "routes": len(new_routes)}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Provision the notification stack")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--skip-policy", action="store_true")
    p.add_argument("--json", action="store_true")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    configure_logging("INFO", json_output=args.json)
    load_dotenv_if_present()

    try:
        webhook = resolve_webhook_url()
    except TeamsWebhookConfigError as exc:
        emit_result({"status": "error", "message": str(exc)}, args.json)
        return 1

    try:
        client = GrafanaClient()  # write token
        client.health()
        result = {
            "status": "ok",
            "dry_run": args.dry_run,
            "template": ensure_template(client, dry_run=args.dry_run),
            "contact_point": ensure_contact_point(client, webhook, dry_run=args.dry_run),
        }
        if not args.skip_policy:
            result["policy"] = ensure_policy(client, dry_run=args.dry_run)
        out = ROOT / "output" / "notification_stack_result.json"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(result, indent=2, default=str), encoding="utf-8")
        emit_result(result, args.json)
        return 0
    except GrafanaError as exc:
        emit_result({"status": "error", "message": str(exc), "body": getattr(exc, "body", None)}, args.json)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
